"""Initial schema: series, markets, candles, trades, weather

Revision ID: 2654f635dce0
Revises: 
Create Date: 2025-11-11 19:43:50.888544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2654f635dce0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.DateTime(), nullable=False),
    sa.Column('series_ticker', sa.String(length=50), nullable=False),
    sa.Column('markets_fetched', sa.Integer(), nullable=True),
    sa.Column('trades_fetched', sa.Integer(), nullable=True),
    sa.Column('candles_1m_generated', sa.Integer(), nullable=True),
    sa.Column('candles_5m_generated', sa.Integer(), nullable=True),
    sa.Column('min_close_date', sa.DateTime(), nullable=True),
    sa.Column('max_close_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ingestion_series_date', 'ingestion_log', ['series_ticker', 'run_date'], unique=False)
    op.create_table('series',
    sa.Column('series_ticker', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('settlement_source_json', sa.JSON(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('series_ticker')
    )
    op.create_table('weather_observed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tmax_f', sa.Float(), nullable=True),
    sa.Column('tmax_c', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'date', name='uq_weather')
    )
    op.create_index('idx_weather_station_date', 'weather_observed', ['station_id', 'date'], unique=False)
    op.create_table('markets',
    sa.Column('ticker', sa.String(length=100), nullable=False),
    sa.Column('series_ticker', sa.String(length=50), nullable=False),
    sa.Column('event_ticker', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('settlement_value', sa.Float(), nullable=True),
    sa.Column('floor_strike', sa.Float(), nullable=True),
    sa.Column('cap_strike', sa.Float(), nullable=True),
    sa.Column('strike_type', sa.String(length=50), nullable=True),
    sa.Column('last_price', sa.Integer(), nullable=True),
    sa.Column('yes_bid', sa.Integer(), nullable=True),
    sa.Column('yes_ask', sa.Integer(), nullable=True),
    sa.Column('no_bid', sa.Integer(), nullable=True),
    sa.Column('no_ask', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('volume_24h', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('liquidity', sa.Integer(), nullable=True),
    sa.Column('rules_primary', sa.Text(), nullable=True),
    sa.Column('rules_secondary', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['series_ticker'], ['series.series_ticker'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index('idx_market_series_close', 'markets', ['series_ticker', 'close_time'], unique=False)
    op.create_index('idx_market_status', 'markets', ['status'], unique=False)
    op.create_index(op.f('ix_markets_status'), 'markets', ['status'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_ticker', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('period_minutes', sa.Integer(), nullable=False),
    sa.Column('open', sa.Integer(), nullable=False),
    sa.Column('high', sa.Integer(), nullable=False),
    sa.Column('low', sa.Integer(), nullable=False),
    sa.Column('close', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('num_trades', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_ticker'], ['markets.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_ticker', 'timestamp', 'period_minutes', name='uq_candle')
    )
    op.create_index('idx_candle_market_time', 'candles', ['market_ticker', 'timestamp'], unique=False)
    op.create_index('idx_candle_period', 'candles', ['period_minutes'], unique=False)
    op.create_table('trades',
    sa.Column('trade_id', sa.String(length=100), nullable=False),
    sa.Column('market_ticker', sa.String(length=100), nullable=False),
    sa.Column('yes_price', sa.Integer(), nullable=False),
    sa.Column('no_price', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('taker_side', sa.String(length=10), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_ticker'], ['markets.ticker'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index('idx_trade_market_time', 'trades', ['market_ticker', 'created_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trade_market_time', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_candle_period', table_name='candles')
    op.drop_index('idx_candle_market_time', table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_markets_status'), table_name='markets')
    op.drop_index('idx_market_status', table_name='markets')
    op.drop_index('idx_market_series_close', table_name='markets')
    op.drop_table('markets')
    op.drop_index('idx_weather_station_date', table_name='weather_observed')
    op.drop_table('weather_observed')
    op.drop_table('series')
    op.drop_index('idx_ingestion_series_date', table_name='ingestion_log')
    op.drop_table('ingestion_log')
    # ### end Alembic commands ###
